### ISSUE TITLE
Missing files in VizWiz Dataset

### ISSUE THREAD

**Issue by chojw** [liqing-ustc/AnswerDiff#1]
Hi, I have tried to run the demo code but it seems that the number of train and val images and annotations don't match. I've checked both the ones in this repo and the annotation file that we can download from https://vizwiz.org/tasks-and-datasets/vizwiz-answer-diff/ yet it seems constantly give an error. Is the dataset being revised? 
Thanks in advance

**Comment by nilavra** [comment]
Hi, We have placed the updated download links on the [website](https://vizwiz.org/tasks-and-datasets/vizwiz-answer-diff/). Please disregard the json files present in the `data` folder, and replace them with the ones available on the VizWiz website. The image counts should match the numbers present on the website.

**Comment by chojw** [comment]
Thanks!
